name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Generate icons
        run: npm run generate:icons

      - name: Check assets consistency
        run: node scripts/check-assets.js

      - name: Create zip artifact
        run: |
          zip -r extension.zip \
            manifest.json background.js content.js \
            popup.html popup.js editor.html editor.js styles.css \
            icons assets

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension-zip
          path: extension.zip

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: chrome-extension-zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: extension.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


